### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by tredoe** [SAP/go-ase#43] opened 2019-12-30 11:01 UTC
Hi! I've tested the Go driver connecting to the master DB but I get an error related to the locale so, I've tried to use the 'isql' tool but I get the same result and I couldn't find any solution at Internet.

```
$ source /opt/sap/SYBASE.sh 
$ isql

The context allocation routine failed when it tried to load localization files!!
One or more following problems may caused the failure

Your sybase home directory is /opt/sap. Check the environment variable SYBASE if it is not the one you want!
Using locale name "es_ES.UTF-8" defined in environment variable LANG
Locale name "es_ES.UTF-8" doesn't exist in your /opt/sap/locales/locales.dat file
An error occurred when attempting to allocate localization-related structures.

$ grep "es_ES.UTF-8" /opt/sap/locales/locales.dat
        locale = es_ES.UTF-8, spanish, utf8
	locale = es_ES.UTF-8@euro, spanish, utf8
	locale = es_ES.UTF-8, spanish, iso15
	locale = es_ES.UTF-8@euro, spanish, iso15
```

**Comment by danielveraec** [comment] 2020-09-09 17:32
Hi.
I have the same problem. Did can you resolve it?

Regards.

**Comment by ntnn** [comment] 2020-09-09 17:47
With which user is the ASE instance installed and with which user are you running your application?
I'd suspect that this is a permission error.

**Comment by danielveraec** [comment] 2020-09-09 19:08
I am trying connect to sybase server from terminal of visual studio code. 
When I connect from cmd is ok, but from de terminal not does it and show me the same message.

**Comment by ntnn** [comment] 2020-09-09 19:33
Is `SYBASE` set in VSCode, as the error message suggests?

Please post the output of the following commands both from the VSCode terminal and the terminal where it works:
```
id
echo $SYBASE
stat $SYBASE/locales/locales.dat
```

**Comment by danielveraec** [comment] 2020-09-09 19:40
Apparently VSCode adds the environment variable LANG = es_ES.UTF-8.
When the terminal tries to connect it, it uses this value.
I can't modify the locales.dat file as the error message suggests. I am not an administrator

**Comment by ntnn** [comment] 2020-09-09 20:30
`LANG` is set by your OS since you have spanish set as your OS language.

`id` prints information about your user - notable the username and associated groups.
`stat` doesn't modify the `locales.dat` - it outputs information about the file, such as ownership and permission bits.

Without this information I won't be able to guess where the issue lies in your setup - not to mention debugging it by replicating it.

**Comment by cb80** [comment] 2020-09-10 06:59
Does [SAP Note 1903433](https://launchpad.support.sap.com/#/notes/1903433) or [SAP Note 2453561](https://launchpad.support.sap.com/#/notes/2453561) help?

**Comment by danielveraec** [comment] 2020-09-10 17:42
> `LANG` is set by your OS since you have spanish set as your OS language (or you have VSCode installed in spanish and VSCode sets it, both is possible).
 
> In any case, a possible workaround would be to set `LANG` to `en_US.UTF-8` or another valid language.

Indeed, the language of my operating system is Spanish and VScode has been installed in English. But the problem is that when Vscode opens the terminal, it sets LANG as Spanish and I can't set it as English. Even if I change it manually, it has no effect.

My workaround for now was to use the Sublime Text 😁 build system.

**Comment by ntnn** [comment] 2020-09-12 05:21
> Even if I change it manually, it has no effect.

Did you export `LANG`? Without exporting the variable won't be propagated to children.

e.g.
```sh
$ echo $LANG
en_ES.UTF-8
$ LANG=en_US.UTF-8
# LANG has been changed for your shell - but not children:
$ sh 'echo $LANG'
en_ES.UTF-8
$ export LANG=es_US.UTF-8
# LANG has been exported, so the variable will be propagated to children:
$ sh 'echo $LANG'
en_US.UTF-8
```

**Comment by ChristianPinilla** [comment] 2021-03-10 19:53
> > Even if I change it manually, it has no effect.
> 
> Did you export `LANG`? Without exporting the variable won't be propagated to children.
> 
> e.g.
> 
> ```shell
> $ echo $LANG
> en_ES.UTF-8
> $ LANG=en_US.UTF-8
> # LANG has been changed for your shell - but not children:
> $ sh 'echo $LANG'
> en_ES.UTF-8
> $ export LANG=es_US.UTF-8
> # LANG has been exported, so the variable will be propagated to children:
> $ sh 'echo $LANG'
> en_US.UTF-8
> ```
Hi, Help me Pls
![image](https://user-images.githubusercontent.com/68829121/110689110-140d0180-81c1-11eb-9db9-9f7efc01f581.png)

**Comment by fwilhelm92** [comment] 2021-03-11 08:06
Hi Chris,

like my colleague @ntnn mentioned, you have to `export` the variable:

```
$ echo $LANG
en_ES.UTF-8
$ LANG=en_US.UTF-8          <--- This does NOT change the variable for its children but only your CURRENT shell
# LANG has been changed for your shell - but not children:
$ sh 'echo $LANG'
en_ES.UTF-8                 <--- Same value as before (In your case the variable is not set, since it was never exported)


$ export LANG=es_US.UTF-8   <--- This does change the variable for its children
# LANG has been exported, so the variable will be propagated to children:
$ sh 'echo $LANG'
en_US.UTF-8                                        
```

**Comment by ChristianPinilla** [comment] 2021-03-11 12:35
> Hi Chris,
> 
> like my colleague @ntnn mentioned, you have to `export` the variable:
> 
> ```
> $ echo $LANG
> en_ES.UTF-8
> $ LANG=en_US.UTF-8          <--- This does NOT change the variable for its children but only your CURRENT shell
> # LANG has been changed for your shell - but not children:
> $ sh 'echo $LANG'
> en_ES.UTF-8                 <--- Same value as before (In your case the variable is not set, since it was never exported)
> 
> 
> $ export LANG=es_US.UTF-8   <--- This does change the variable for its children
> # LANG has been exported, so the variable will be propagated to children:
> $ sh 'echo $LANG'
> en_US.UTF-8                                        
> ```

I am from Windows. I exported the variable, but i can't use the sh command. Help me pls, its important for my job :C
![image](https://user-images.githubusercontent.com/68829121/110788176-0e5cfd80-824d-11eb-9d7c-2bc3d59b6a7a.png)
![image](https://user-images.githubusercontent.com/68829121/110788217-1b79ec80-824d-11eb-8ada-60b6cf187140.png)

**Comment by fwilhelm92** [comment] 2021-03-11 12:53
You could try `export LANG=en_US.UTF-8`

**Comment by cb80** [comment] 2021-03-11 13:05
Usually LANG is already exported. To get the complete picture you may try to replicate the following commands in your environment and see if that improves things:
```
$ unset LANG
$ echo $LANG

$ LANG=en_ES.UTF-8
$ echo $LANG
en_ES.UTF-8
$ bash -c 'echo $LANG'

$ export LANG=en_ES.UTF-8
$ bash -c 'echo $LANG'
en_ES.UTF-8
```

However the error message you show tells that `es_419.UTF-8` does not exist in the `locales.dat` file. Please check that!

**Comment by cb80** [comment] 2021-03-11 13:07
As this is not related to the go-ase driver but to your specific environment I am closing this.

**Closed by cb80** 2021-03-11 13:07 UTC
